#!/bin/sh

echo "running backup script at"
date

NC="/usr/bin/nc"
RESTIC="/usr/local/bin/restic"

while ! "$NC" -zw1 google.com 443; do
    echo "waiting for connection"
    sleep 5
done

. /Users/arul/scripts/.restic-env

"$RESTIC" backup /Users/arul/code /Users/arul/dotfiles /Users/arul/Documents /Users/arul/Pictures /Users/arul/.config/gnupg /Users/arul/.ssh --exclude={node_modules,target,plugged,autoload}

"$RESTIC" forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 2 --keep-yearly 1
