#!/bin/sh

echo "running backup script at"
date

NC="/usr/bin/nc"
RESTIC="/usr/local/bin/restic"
ARUL="/Users/arul"

while ! "$NC" -zw1 google.com 443; do
    echo "waiting for connection"
    sleep 5
done

backup () {
    "$RESTIC" backup $ARUL/code $ARUL/cloud  $ARUL/dotfiles $ARUL/Documents $ARUL/Pictures $ARUL/.config/gnupg $ARUL/.ssh --exclude={node_modules,target,plugged,autoload}

    "$RESTIC" forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 2 --keep-yearly 1
}


. /Users/arul/scripts/.restic.env && backup
. /Users/arul/scripts/.scaleway.env && backup
. /Users/arul/scripts/.oracle.env && backup
