#!/bin/bash

#                 ██      ██          ██
#                ░██     ░██         ░██
#  ██████ ██   ██░██     ░██  ██     ░██
# ██░░░░ ░░██ ██ ░██████ ░██ ██   ██████
#░░█████  ░░███  ░██░░░██░████   ██░░░██
# ░░░░░██  ██░██ ░██  ░██░██░██ ░██  ░██
# ██████  ██ ░░██░██  ░██░██░░██░░██████
#░░░░░░  ░░   ░░ ░░   ░░ ░░  ░░  ░░░░░░ 

#
# wm independent hotkeys
#

# open st
super + Return
    st

# open alacritty
super + shift + Return
    alacritty

# scratchpad/dropdown
super + d
    ~/scripts/bspwm/dropdown.sh

# draw a terminal window
super + shift + d
    bspc rule -a \* -o state=floating rectangle=$(slop -f "%g") && st

# save song to spotify
super + alt + s
    ~/scripts/go/spotify_add; \
    dunstify -u normal "Song added to spotify";

# preselect in reverse fashion to normal
super + ctrl + Return
    ~/scripts/bspwm/auto-presel.sh

# program launcher - rofi
super + @space
	rofi -show combi -theme drac -terminal st -font "SF Pro Display 14" -matching fuzzy


# launch browser - chromium/firefox
super + {_,shift + }b
	{chromium, google-chrome-stable}

# launch vscodium
super + v
    vscodium

# launch lf/pcmanfm
super + {_,shift + }f
    {st -e lf, pcmanfm}

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# launch youtube dmenu
super + y
    ~/scripts/bin/dmenu_youtube

# lock screen
super + ctrl + alt + l
	~/scripts/rice/lock.sh

# take screenshot
Print
    ~/scripts/utility/screenshot.sh;

# take region screensho TODO: currently broken
shift + Print
    ~/scripts/utility/screenshot.sh area;

# reload bars
super + shift + r
    pkill polybar && polybar -r burs & disown; \
    polybar -r bur & disown;

#
# bspwm keybinds
#

# quit bspwm normally
super + alt + Escape
	bspc quit

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# rotate desktop
super + {_,shift + }r
	bspc node @/ --rotate {90,-90}

# insert receptacle, or cleanr receptacles on current desktop
super + {_,shift} + i
    insert={true,false}; \
    $insert && bspc node -i || \
    for win in `bspc query -N -n .leaf.!window`; do bspc node $win -k ; done;

# circulate the leaves of the tree
super + c
    clipmenu

# make split ratios equal
super + equal
	bspc node @/ --equalize

# make split ratios balanced
super + minus
	bspc node @/ --balance

# send window to other monitor
super + shift + m
    bspc node -m next

# focus next monitor
super + m
    bspc monitor -f next

# swap the desktops of the monitors
super + ctrl + shift + m
    bspc desktop -s next:focused

# send the focused node to the newest preselected node
super + shift + y
	bspc node focused.local -n newest.!automatic.local

# swap the current node and the biggest node
super + shift + g
	bspc node -s biggest.local

#
# state/flags
#

# set the window state; t to swap tiled/floating and f for fullscreen
super + s; {t,f}
	bspc node -t {$(bspc query -N -n -n .tiled > /dev/null && echo floating || echo tiled),fullscreen}

# mark a node
super + ctrl + m
	bspc node -g marked

#
# focus/swap
#

# focus/swap the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# warp window in the given direction
super + ctrl + shift + {h,j,k,l}
    bspc node -n {west,south,north,east} --follow
    #~/scripts/bspwm/warp.sh {west,south,north,east}

# focus the next/previous occupied desktop in the current monitor
super + {q,e}
	bspc desktop -f {prev,next}.local.occupied

# focus the next/previous occupied desktop in the current monitor
super + ctrl + {q,e}
	bspc desktop -f {prev,next}.local

# send to next/previous desktop in current monitor
super + shift + {q,e}
    bspc node -d {prev,next}.local

# focus the last desktop that has stuff in this monitor
super + grave
	bspc desktop -f last.occupied.local

# focus the next/previous node in the current desktop
super + {_,shift + }Tab
    bspc node -f {next,prev}.local

# focus the older or newer node in the focus history
#super + {o,i}
#    bspc wm -h off; \
#    bspc node {older,newer} -f; \
#    bspc wm -h on

# focus to the given desktop
super + {1-9}
    bspc desktop -f 'focused:^{1-9}'

# send node to desktop on current monitor
super + shift + {1-9}
    bspc node -d 'focused:^{1-9}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel all preselections
super + ctrl + space
    for window in $(bspc query -N); do bspc node $window -p cancel; done

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}


##Media Keys
# Raise volume
XF86AudioRaiseVolume
	pactl set-sink-volume 0 +5%

# Lower Volume
XF86AudioLowerVolume
	pactl set-sink-volume 0 -5%

XF86AudioMute
	pamixer -t

XF86AudioPlay
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

XF86AudioPrev
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous

XF86AudioNext
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
