#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
    (dropdown) echo state=floating \ desktop=focused:focused \ private=true \ hidden=true;;
    (Firefox|Chromium) echo \ desktop=^2:^1;;
    ([dD]iscord) echo desktop=^1:^1;;
    ([zZ]athura) echo state=tiled;;
    (Spotify) echo desktop=^1:^2;;
    ([sS]urf) echo state=tiled;;
    #games
    ([sS]team) echo desktop=^2:8 \ state=floating;;
    (dota2) echo desktop=^2:^9;;
    ('')
        case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
            (spotify) echo desktop=^1:^2;;
        esac;;
esac;

# vim: set ft=sh :
