#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
class=$2;
instance=$3;
title=$(xtitle "$id")
printf "id %s\nclass %s\ninst %s\ntitle %s\n\n" "$id" "$class" "$instance" "$title" >> /tmp/extout.txt

case $class in
    (dropdownterm.Alacritty) echo state=floating \ desktop=focused:focused \ hidden=true;;
    (Firefox|Chromium) echo \ desktop=^2:^1;;
    ([dD]iscord) echo desktop=^1:^1;;
    ([zZ]athura) echo state=tiled;;
    (Spotify) echo desktop=^1:^2;;
    ([sS]urf) echo state=tiled;;
    ([eE]macs) echo state=tiled;;
    #games
    ([sS]team) echo desktop=^2:^8 \ state=tiled;;
    (dota2) echo desktop=^2:^9 \ state=fullscreen;;
    (factorio) echo desktop=^2:^9 \ state=fullscreen;;
    ('')
        case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
            (spotify) echo desktop=^1:^2;;
        esac;;
esac;

case $title in
    ('Friends List') echo state=floating \ desktop=^2:^8;;
esac;
# vim: set ft=sh :
