#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
    (Firefox|Firefox-esr|Iceweasel|Chromium) echo \ desktop=^2:^1;;
    (dota2) echo desktop=^2:^9;;
	(Spotify) echo desktop=^2\ monitor=^1;;
	([sS]urf) echo state=tiled;;
	('')
		case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
			(spotify) echo desktop=^2\ monitor=^1;;
		esac;;
esac;

# vim: set ft=sh :
