#!/bin/bash
#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░


bspc monitor HDMI-0 -d cero uno dos tres cuatro cinco seis siete ocho nueve
bspc monitor eDP-1-1 -d cero uno dos tres cuatro cinco seis siete ocho nueve 
xrdb ~/.Xresources

background="#231E18"
red="#FF5C57"
gold="#F3F99D"
grassy="#B7BA53"
green="#5AF78E"
blue="#9AEDFE"
teal="#57C7FF"
brown="#B49368"
#theming
bspc config normal_border_color		"$green"
bspc config active_border_color		"$teal"
bspc config focused_border_color	"$gold"
bspc config presel_feedback_color	"$green"

bspc config border_width    0
bspc config window_gap      20
bspc config top_padding 	8
bspc config right_padding	8
bspc config bottom_padding 	8
bspc config left_padding 	8
bspc config ignore_ewmh_struts true


bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor false
# window rules
bspc config external_rules_command ~/.config/bspwm/bspwm-rules #most of the rules are in here

# Autostart
feh --bg-fill ~/githubs/others/wallpapers/scenery/art/pixelLushAlley.jpg
~/scripts/bspwm/desktop.sh &
~/scripts/bspwm/defaultsetup.sh &

dunstify -u critical "system" "everything is up and running"
