#!/usr/bin/env sh

# load the scripting addon
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

alias yc='yabai -m config'
alias yr='yabai -m rule --add'

# global settings
yc mouse_follows_focus          off
yc focus_follows_mouse          off
yc window_placement             second_child
yc window_topmost               on
yc window_opacity               off
yc window_opacity_duration      0.0
yc window_shadow                on
yc active_window_opacity        1.0
yc normal_window_opacity        1.0 
yc split_ratio                  0.50
yc auto_balance                 off
yc mouse_modifier               ctrl
yc mouse_action1                move
yc mouse_action2                resize

# general space settings
yc layout                       bsp
yc external_bar                 all:20:0
yc top_padding                  20
yc bottom_padding               20
yc left_padding                 20
yc right_padding                20
yc window_gap                   10


# yabai rules
yr title='Preferences' manage=off layer=above
yr title='^(Opening)' manage=off layer=above
yr app='System Preferences' manage=off layer=above
yr app='App Store' manage=off layer=above
yr app='IINA' manage=off layer=above
yr app='Numi' manage=off layer=above
yr app='Finder' manage=off layer=above
yr app='Keka' manage=off layer=above
yr app='Contexts' manage=off layer=above
yr app='Deepl*' manage=off layer=above
yr app='ProtonVPN' manage=off layer=above
yr app='ExpressVPN' manage=off layer=above
yr app='nordVPN' manage=off layer=above


#yr app='Firefox' space=1
#yr app='Safari' space=1
yr app='Dofus'   space=2
yr app='Discord' space=5
yr app='Spotify' space=6


# yabai signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"pecan-workspace-jsx\"'"
yabai -m signal --add event=space_changed action="landscape"

echo "yabai configuration loaded!"
open -na Discord
open -na Spotify
